name: Trigger auto deployment for continuous-deployment-test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - 'dockerfile/**'
    - '.github/workflows/continuous-deployment-test-AutoDeployTrigger-fce0b219-92d2-42da-aee5-4fa7ba7d477c.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTINUOUSDEPLOYMENTTEST_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/dockerfile 
          registryUrl: https://kmalyalareg.azurecr.io
          registryUsername: ${{ secrets.CONTINUOUSDEPLOYMENTTEST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTINUOUSDEPLOYMENTTEST_REGISTRY_PASSWORD }}
          containerAppName: continuous-deployment-test
          resourceGroup: Containerapp
          imageToBuild: https://kmalyalareg.azurecr.io/continuous-deployment-test:${{ github.sha }}
          dockerfilePath: Dockerfile

     

